"""add_created_at_to_comments

Revision ID: 2e7dffff41f4
Revises: 225900c76a29
Create Date: 2025-12-06 13:54:56.426440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7dffff41f4'
down_revision: Union[str, Sequence[str], None] = '225900c76a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'card_assignees', ['id'])
    op.add_column('comments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'created_at')
    op.drop_constraint(None, 'card_assignees', type_='unique')
    # ### end Alembic commands ###
